### PR TITLE
Update dependencies and remove vendor directory

### PR DESCRIPTION
**Pull request by gabrieljackson**
```release-note
None
```

### CODE REVIEW

**Review by nickmisasi — COMMENTED** [review]
Should we even be committing the vendor folder at all?

**Comment by gabrieljackson** [comment]
> Should we even be committing the vendor folder at all?

Not really necessary so I agree we can get rid of it. New commits pushed removing vendor dir.

**Review by nickmisasi — APPROVED** [review]
Probably want to add vendor to .gitignore as well

**Review by fmartingr — APPROVED** [review]
LGTM! (I stopped reviewing after the go.sum file)

**Pull request merged**
